version: '3'
services:
  web:
    build: .
    ports:
      - '8011:8011'
    depends_on:
      - influx

  mqtt:
    image: ansi/mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883

  influx:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=name
