version: '3'
services:
  runme:
    build: .
    environment:
      - DISPLAY=${HOSTNAME}:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  influx:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=name
